create TABLE PRODUCT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE BIGINT CHECK (PRICE > 0),
    CREATED TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP NOT NULL
);

create TABLE CATEGORY (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

create TABLE PRODUCT_CATEGORIES (
    PRODUCT_ID BIGINT,
    CATEGORY_ID BIGINT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    PRIMARY KEY (PRODUCT_ID, CATEGORY_ID)
);
